# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kio': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kdoctools': '@stable'
    'third-party/qtkeychain': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]      
